# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 878dc240dfa5cf7100148b3c80fd39349d5a06417f4c710e6d77a02d90c5f91b85f00df8f9917f92f44e6a529ac519248903acd7cce003078078b8265e0f20f1

test:
  secret_key_base: b7b0f3d680962530919c8783353e7fbbf7b949775ba08f0c6cc8ff18c64d745b0144ffabb89c12d101ec309b1b825dd4d67764c5ed70fc36dd18b790534b6095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
